# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0af688017df978b40ae54541459655b1114cc57ad7dce71a15511b1b45c76de1fb1e8f51726477178da10f846fa4d9bf0fc20c4ecf7438763c667398339aa16e

test:
  secret_key_base: 469e674c8181d8f912375afd7cbba14d52dbb19f640d316365a58fe70f6fd782d2dc048d3d93d0103c66d735646c28aa9d01c3c175f271a1c4de4564e8ac8f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
